[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@uniswap/permit2/=lib/permit2/",
    "@uniswap/universal-router/=lib/universal-router/",
    "@uniswap/v3-core/=lib/v3-core/contracts/",
    "@uniswap/v2-core/=lib/v2-core/contracts/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "solady=lib/solady/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
